export const IMAGES = {
  clock: require('./clock.png'),
  searchIcon: require('./search-icon.png'),
  thumbsUp: require('./thumbs-up.gif'),
  thumbsDown: require('./thumbs-down.gif'),
  like: require('./like.png'),
  comments: require('./comments.png'),
  bookmark: require('./bookmark.png'),
  share: require('./share.png'),
  musicPlayer: require('./music-player.png'),
  forwardIcon: require('./forward.png'),
  homeIcon: require('./home.png'),
  discoverIcon: require('./discover.png'),
  activityIcon: require('./activity.png'),
  bookmarkIcon: require('./bookmarks.png'),
  profileIcon: require('./profile.png'),
};
